version: 0.2

env:
    variables:
        APP_NAME: "angular-cicd-pipeline"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - rm package-lock.json
  pre_build:
    commands:
        - npm install      
  build:
    commands:
        - echo Build started 
        - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://my-awsome-bucket-of-files-code --delete     
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
